### ISSUE TITLE
Recent zero-initialization triggers `-Wreturn-type-c-linkage` when building generated code with `clang++`

### ISSUE THREAD

**Issue by anforowicz** [dtolnay/cxx#1497]
During a recent attempt to roll `cxx` to a new version in Chromium, we discovered that the code generated by `cxx` results in a Clang warning that didn't happen before.  I am opening an issue to capture what I learned so far, but I admit that I didn't really dig deeper into the issue...  but I _assume_ that the problem pointed out by the warning is real?

REPRO:

* `export CXXFLAGS="-Werror -Wall -std=c++14"`
    - C++14 because `CXX_DEFAULT_VALUE` expands to "nothing" in earlier C++ versions - see [here](https://github.com/dtolnay/cxx/blob/dfecf55cb2dfb825a6c2541b6f43d06040c9c41a/gen/src/write.rs#L51-L55)
    - `-Werror` and `-Wall` to error out if `-Wreturn-type-c-linkage` is reported
* `export CXX=clang++`
    - The problem doesn't repro with the default `c++` compiler
    - The problem originally repro-ed with Chromium-provided compiler (nightly version of Clang), but it also repros with what I have installed on my system:
 
        ```
        $ clang++ --version
        Debian clang version 19.1.7 (1)
        Target: x86_64-pc-linux-gnu
        Thread model: posix
        InstalledDir: /usr/lib/llvm-19/bin
        ```
* `git checkout ead032256713c6aa0de3b410417357b3e44ce5ab`
    - ead032256713c6aa0de3b410417357b3e44ce5ab is what the problem has bisected to.  The problem doesn't repro at an earlier commit.
* `cargo test`

```
$ cargo test
   Compiling cxx-test-suite v0.0.0 (/usr/local/google/home/lukasza/src/github/cxx/tests/ffi)
warning: cxx-test-suite@0.0.0: /usr/local/google/home/lukasza/src/github/cxx/target/debug/build/cxx-test-suite-6288a940afe915f9/out/cxxbridge/sources/tests/ffi/lib.rs.cc:1471:17: error: 'tests$cxxbridge1$c_return_shared' has C-linkage specified, but returns user-defined type '::tests::Shared' which is incompatible with C [-Werror,-Wreturn-type-c-linkage]
warning: cxx-test-suite@0.0.0:  1471 | ::tests::Shared tests$cxxbridge1$c_return_shared() noexcept {
warning: cxx-test-suite@0.0.0:       |                 ^
warning: cxx-test-suite@0.0.0: /usr/local/google/home/lukasza/src/github/cxx/target/debug/build/cxx-test-suite-6288a940afe915f9/out/cxxbridge/sources/tests/ffi/lib.rs.cc:2180:17: error: 'tests$cxxbridge1$r_return_shared' has C-linkage specified, but returns user-defined type '::tests::Shared' which is incompatible with C [-Werror,-Wreturn-type-c-linkage]
warning: cxx-test-suite@0.0.0:  2180 | ::tests::Shared tests$cxxbridge1$r_return_shared() noexcept;
warning: cxx-test-suite@0.0.0:       |                 ^
warning: cxx-test-suite@0.0.0: 2 errors generated.
error: failed to run custom build command for `cxx-test-suite v0.0.0 (/usr/local/google/home/lukasza/src/github/cxx/tests/ffi)`

Caused by:
  process didn't exit successfully: `/usr/local/google/home/lukasza/src/github/cxx/target/debug/build/cxx-test-suite-9dcdb3acfd78f563/build-script-build` (exit status: 1)
  --- stdout
  cargo:CXXBRIDGE_PREFIX=tests/ffi
  cargo:CXXBRIDGE_DIR0=/usr/local/google/home/lukasza/src/github/cxx/target/debug/build/cxx-test-suite-6288a940afe915f9/out/cxxbridge/include
  cargo:CXXBRIDGE_DIR1=/usr/local/google/home/lukasza/src/github/cxx/target/debug/build/cxx-test-suite-6288a940afe915f9/out/cxxbridge/crate
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CXX_x86_64-unknown-linux-gnu
  CXX_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CXX_x86_64_unknown_linux_gnu
  CXX_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CXX
  HOST_CXX = None
  cargo:rerun-if-env-changed=CXX
  CXX = Some("clang++")
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64-unknown-linux-gnu
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64_unknown_linux_gnu
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = Some("-Werror -Wall -std=c++14")
  running: "clang++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64" "--target=x86_64-unknown-linux-gnu" "-std=c++11" "-Werror" "-Wall" "-std=c++14" "-I" "/usr/local/google/home/lukasza/src/github/cxx/target/debug/build/cxx-test-suite-6288a940afe915f9/out/cxxbridge/include" "-I" "/usr/local/google/home/lukasza/src/github/cxx/target/debug/build/cxx-test-suite-6288a940afe915f9/out/cxxbridge/crate" "-DCXX_TEST_INSTANTIATIONS" "-o" "/usr/local/google/home/lukasza/src/github/cxx/target/debug/build/cxx-test-suite-6288a940afe915f9/out/3d273691970f498d-lib.rs.o" "-c" "/usr/local/google/home/lukasza/src/github/cxx/target/debug/build/cxx-test-suite-6288a940afe915f9/out/cxxbridge/sources/tests/ffi/lib.rs.cc"
  cargo:warning=/usr/local/google/home/lukasza/src/github/cxx/target/debug/build/cxx-test-suite-6288a940afe915f9/out/cxxbridge/sources/tests/ffi/lib.rs.cc:1471:17: error: 'tests$cxxbridge1$c_return_shared' has C-linkage specified, but returns user-defined type '::tests::Shared' which is incompatible with C [-Werror,-Wreturn-type-c-linkage]
  cargo:warning= 1471 | ::tests::Shared tests$cxxbridge1$c_return_shared() noexcept {
  cargo:warning=      |                 ^
  cargo:warning=/usr/local/google/home/lukasza/src/github/cxx/target/debug/build/cxx-test-suite-6288a940afe915f9/out/cxxbridge/sources/tests/ffi/lib.rs.cc:2180:17: error: 'tests$cxxbridge1$r_return_shared' has C-linkage specified, but returns user-defined type '::tests::Shared' which is incompatible with C [-Werror,-Wreturn-type-c-linkage]
  cargo:warning= 2180 | ::tests::Shared tests$cxxbridge1$r_return_shared() noexcept;
  cargo:warning=      |                 ^
  cargo:warning=2 errors generated.
  exit status: 1
```
