### ISSUE TITLE
Trouble using rust::Vec<rust::String> as function argument

### ISSUE THREAD

**Issue by crysty013** [dtolnay/cxx#564]
I'm trying to write a parser for a pet project and I'm hitting multiple issues interfacing through `cxx`. This involves constructing an object from a vector of strings.

Snippets:

<details>
<summary>Header</summary>

```cpp
#pragma once

#include "rust/cxx.h"

#include <memory>

namespace app {
    class Parser {
    public:
        // Parser(const rust::Vec<rust::String>& cmdline_args): m_cmdline_args(cmdline_args);
        // constructor initialization list broken
        Parser(const rust::Vec<rust::String>& cmdline_args);
    
    private:
        rust::Vec<rust::String> m_cmdline_args;
    };

    std::unique_ptr<Parser> new_parser(const rust::Vec<rust::String>& cmdline_args);
}
```
</details>

<details>
<summary>CPP source</summary>

```cpp
#include "parser/include/parser.hpp"

#include <iostream>

namespace app {
    Parser::Parser(const rust::Vec<rust::String>& cmdline_args) {
        // this->m_cmdline_args = cmdline_args;
        // assignment operator broken
        this->m_cmdline_args = {};

        for (auto arg: cmdline_args) {
            this->m_cmdline_args.push_back(arg);
        }

        std::cout << "Hello, world!" << std::endl;
    }

    std::unique_ptr<Parser> new_parser(const rust::Vec<rust::String>& cmdline_args) {
        return std::make_unique<Parser>(new Parser(cmdline_args));
    }
}
```
</details>

<details>
<summary>Rust source lib.rs</summary>

```rust
#[cxx::bridge(namespace = "app")]
pub mod ffi {
    unsafe extern "C++" {
        include!("parser/include/parser.hpp");

        type Parser;

        fn new_parser(cmdline_args: Vec<String>) -> UniquePtr<Parser>;
    }
}
```
</details>

1. On the C++ side, initialization-list constructors don't seem to work.
1. There's also some trouble with the assignment `operator=` between a `rust::Vec<rust::String>` and a `const rust::Vec<rust::String>&` which makes it tricky to adhere to idiomatic C++.
1. Even with workarounds (no init list in constructor, no `operator=` - instead using `push_back` in a `for` loop), the snippet above still doesn't compile with `cxx` and `cxx-build` **v1.0.15**. The errors seem to revolve around the use of `const &` with `Vec` arguments.

What's the recommended way of passing a vector of strings around as function args?

**Comment by dtolnay** [comment]
The build error I get from the files you shared is:

```console
example-36032d026cad2abb/out/cxxbridge/sources/parser/src/main.rs.cc: In function ‘app::Parser* app::app$cxxbridge1$new_parser(const rust::cxxbridge1::Vec<rust::cxxbridge1::String>*)’:
example-36032d026cad2abb/out/cxxbridge/sources/parser/src/main.rs.cc:467:89: error: invalid conversion from ‘std::unique_ptr<app::Parser> (*)(const rust::cxxbridge1::Vec<rust::cxxbridge1::String>&)’ to ‘std::unique_ptr<app::Parser> (*)(rust::cxxbridge1::Vec<rust::cxxbridge1::String>)’ [-fpermissive]
  467 |   ::std::unique_ptr<::app::Parser> (*new_parser$)(::rust::Vec<::rust::String>) = ::app::new_parser;
      |                                                                                  ~~~~~~~^~~~~~~~~~
      |                                                                                         |
      |                                                                                         std::unique_ptr<app::Parser> (*)(const rust::cxxbridge1::Vec<rust::cxxbridge1::String>&)
```

which means that CXX is expecting your signature to be `std::unique_ptr<Parser> new_parser(rust::Vec<rust::String>)` whereas your actual signature is `std::unique_ptr<Parser> new_parser(const rust::Vec<rust::String>&)`.

If you meant for the signature to be `fn new_parser(Vec<String>) -> UniquePtr<Parser>` in Rust, you need to provide `std::unique_ptr<Parser> new_parser(rust::Vec<rust::String>)` in C++. Alternatively if you meant for the signature to be `std::unique_ptr<Parser> new_parser(const rust::Vec<rust::String>&)` in C++, you need to write it as `fn new_parser(cmdline_args: &Vec<String>) -> UniquePtr<Parser>` in Rust. They need to be consistent.

After that you'll also need to change:

```diff
- return std::make_unique<Parser>(new Parser(cmdline_args));
+ return std::make_unique<Parser>(cmdline_args);
```

or:

```diff
- return std::make_unique<Parser>(new Parser(cmdline_args));
+ return std::unique_ptr<Parser>(new Parser(cmdline_args));
```

since there is no constructor `Parser::Parser(Parser *)`.

For rust::Vec copy construction, it just wasn't implemented yet. I've added those in cxx 1.0.16.

```cpp
Parser::Parser(const rust::Vec<rust::String>& cmdline_args)
    : m_cmdline_args(cmdline_args) {}

// or

Parser::Parser(const rust::Vec<rust::String>& cmdline_args) {
    this->m_cmdline_args = cmdline_args;
}
```

**Comment by crysty013** [comment]
Ah, I missed the reference & on the Rust side - thank you for pointing me in the right direction! As for the copy constructors, I'm glad to hear they're coming up shortly. Thank you for your help!
